platform :ios do
  lane :ios_build_app do |options|
    build_app(
      destination: "generic/platform=iOS",
      workspace: "./ios/AuthgearDemoAppRN.xcworkspace",
      scheme: "AuthgearDemoAppRN",
      configuration: "Release",
      export_options: "./ios/ExportOptions.plist",
      clean: true,
      output_directory: "./build/Release/iOS/AuthgearDemoAppRN",
      output_name: "AuthgearDemoAppRN.ipa",
      xcargs: "CURRENT_PROJECT_VERSION=#{options[:CURRENT_PROJECT_VERSION]}",
    )
  end

  lane :ios_upload_app do
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: "./build/fastlane-api-key.json",
      ipa: "./build/Release/iOS/AuthgearDemoAppRN/AuthgearDemoAppRN.ipa"
    )
  end
end

platform :android do
  lane :build_aab do |options|
    gradle(
      project_dir: "./android",
      tasks: [":app:bundleRelease"],
      properties: {
        "VERSION_CODE" => options[:VERSION_CODE],
        "STORE_FILE" => options[:STORE_FILE],
        "STORE_PASSWORD" => options[:STORE_PASSWORD],
        "KEY_ALIAS" => options[:KEY_ALIAS],
        "KEY_PASSWORD" => options[:KEY_PASSWORD],
      },
    )
  end

  lane :upload_aab do |options|
    upload_to_play_store(
      json_key: options[:json_key],
      package_name: "com.authgear.exampleapp.reactnativeforsales",
      track: "internal",
      aab: "./android/app/build/outputs/bundle/release/app-release.aab",
    )
  end
end
