name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'
  workflow_dispatch: {}
  schedule:
  - cron: "35 9 * * THU"

jobs:
  react_native_ios:
    if: ${{ github.repository == 'authgear/authgear-demo-app-rn' }}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./.tool-versions"
    - uses: ruby/setup-ruby@v1
      with:
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - run: make npm-ci
    - run: make pod-install
    - uses: authgear/gh-actions-install-apple-certificate-and-provisioning-profile@v1
      with:
        certificate_base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
        certificate_password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        provisioning_profile_base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        keychain_password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
    - uses: authgear/gh-actions-create-fastlane-api-key-json-file@v1
      with:
        api_key_id: ${{ secrets.IOS_API_KEY_ID }}
        api_key_issuer: ${{ secrets.IOS_API_KEY_ISSUER }}
        api_key_base64: ${{ secrets.IOS_API_KEY_BASE64 }}
        output_path: ./build/fastlane-api-key.json
    - run: make ios-build-app
    - run: make ios-upload-app
      if: ${{ github.ref == 'refs/heads/master' }}

  react_native_android:
    if: ${{ github.repository == 'authgear/authgear-demo-app-rn' }}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./.tool-versions"
    - uses: ruby/setup-ruby@v1
      with:
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - run: make npm-ci
    - name: Build aab
      env:
        STORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        export STORE_FILE="$RUNNER_TEMP/upload_key.jks"
        echo -n "$STORE_BASE64" | base64 --decode -o "$STORE_FILE"
        make build-aab
    - name: Upload aab
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
      run: |
        export GOOGLE_SERVICE_ACCOUNT_KEY_JSON_FILE="$RUNNER_TEMP/google_service_account_key.json"
        echo -n "$GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64" | base64 --decode -o "$GOOGLE_SERVICE_ACCOUNT_KEY_JSON_FILE"
        make upload-aab
