name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  react_native_ios:
    if: github.ref == 'refs/heads/master'
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - run: sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
    - run: npm install -g appcenter-cli
    - run: yarn install
    - working-directory: ./ios
      run: pod install
    - name: Install the Apple certificate and provisioning profile
      env:
        IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
        IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        echo -n "$IOS_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        security create-keychain -p "" $KEYCHAIN_PATH
        security set-keychain-settings $KEYCHAIN_PATH
        security unlock-keychain -p "" $KEYCHAIN_PATH

        security import $CERTIFICATE_PATH -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
    - name: Set CFBundleVersion
      working-directory: ./ios
      run: |
        BUILD_NUMBER=$(date +%s)
        /usr/libexec/Plistbuddy -c "Set CFBundleVersion $BUILD_NUMBER" ./AuthgearDemoAppRN/Info.plist
    - name: Run xcodebuild archive
      working-directory: ./ios
      run: xcodebuild -workspace AuthgearDemoAppRN.xcworkspace -scheme AuthgearDemoAppRN -configuration Release -archivePath "$RUNNER_TEMP/AuthgearDemoAppRN.xcarchive" archive
    - name: Run xcodebuild -exportArchive
      working-directory: ./ios
      run: xcodebuild -exportArchive -archivePath "$RUNNER_TEMP/AuthgearDemoAppRN.xcarchive" -exportPath "$RUNNER_TEMP/AuthgearDemoAppRN.export" -exportOptionsPlist "./ExportOptions.plist"
    - name: Distribute to App Center
      env:
        APPCENTER_ACCESS_TOKEN: ${{ secrets.IOS_APPCENTER_ACCESS_TOKEN }}
      run: appcenter distribute release --debug --silent --file "$RUNNER_TEMP/AuthgearDemoAppRN.export/AuthgearDemoAppRN.ipa" --store "App Store Connect Users" --app "Oursky/Authgear-demo-app-react-native-for-sales" --release-notes "no release notes"
    - name: Clean up keychain and provisioning profile
      if: ${{ always() }}
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
